### ISSUE TITLE
Unable to load in IL2CPP build

### ISSUE THREAD

**Issue by XenuIsWatching** [Skurdt/SK.Libretro#10]
For IL2CPP, it is unable to marshalling delegates to an instanced methods

```
System.NotSupportedException: IL2CPP does not support marshaling delegates that point to instance methods to native code. The method we're attempting to marshal is: SK.Libretro.EnvironmentHandler::EnvironmentCallback
```
which comes from the function in the call stack
https://github.com/Skurdt/SK.Libretro/blob/cf14f8392a40119542a9e0d66a89d096ec4aa4db/Scripts/Core.cs#L293

**Comment by Skurdt** [comment]
In c++, all the needed callbacks have to be global functions, either as static member functions in classes, or a free functions.

You could mark the SetCallbacks() method as static, then modify all the needed functions and members and mark them as static as well.
It will basically make the majority of the code static, so only doing this will prevent multiple instances running at the same time.
If this even works, supporting multiple instances can probably be done using a list/queue containing data for each instances.

**Comment by XenuIsWatching** [comment]
yeah... I'm looking into it myself right now. I first just basically just put every instance into a Dictionary when constructed.... but still trying to figure out how to "look up" which instance it is when the core callbacks in to the static function.

I just made it single instanced (static) to keep moving while I think about it, and it's now just whack-a-mole of issues trying to get it to run on Android such as `Marshal.GetFunctionPointerForDelegate` needs to call static functions as well

**Comment by Skurdt** [comment]
It should run on Android without using il2cpp though.

I think the only change that was needed was to use persistentdatapath instead of streamingassetspath and load files using unitywebrequest instead of read/write to file.

**Comment by XenuIsWatching** [comment]
> It should run on Android without using il2cpp though.

The ARM64 option gets "grayed out" for Mono, I haven't tried running it with the target arch of ARMv7 yet...

> I think the only change that was needed was to use persistentdatapath instead of streamingassetspath and load files using unitywebrequest instead of read/write to file.

yeah, I already did.... there is also the issue of where dynamic libraries can be loaded. Due to "security reasons", they can only be loaded from the private app directory which I just retrieved with the function
```cs
    private string GetAndroidPrivateAppDataPath()
    {
        string path;
        using (AndroidJavaClass jc = new AndroidJavaClass("com.unity3d.player.UnityPlayer"))
        {
            using (AndroidJavaObject currentActivity = jc.GetStatic<AndroidJavaObject>("currentActivity"))
            {
                path = currentActivity.Call<AndroidJavaObject>("getFilesDir").Call<string>("getCanonicalPath");
            }
        }
        return path;
    }
```

**Comment by XenuIsWatching** [comment]
> It's probably more a hack than anything but, if running with the included classes, you might be able to use a Dictionary<Thread, XYZ> and look up for the data using Thread.CurrentThread.

That could work... The only caveat I can come up with is if the libretro core creates its own threads and then calls the callback function

**Comment by gtk2k** [comment]
I'm trying to build Android (Quest), but for now I can get to the point where the so file is copied to the temp folder ($"{GetAndroidPrivateAppDataPath()}/temp"),
```
Error Unity Exception: Function 'retro_init' not found in library 'mame2003_plus_0a41927c-22d2-4c0b-9f46-128abe8a21ab' at path '/data/data/com.DefaultCompany.Android_Arcade/files/temp/mame2003_plus_0a41927c-22d2-4c0b-9f46-1 28abe8a21ab .so' (D)
```
function acquisition fails.
Is there any workaround?
