### ISSUE TITLE
Nestopia core input does not work on Windows platform.

### ISSUE THREAD

**Issue by Phantomxm2021** [Skurdt/SK.Libretro#21]
Nestopia core input does not work on Windows platform.

**Comment by Skurdt** [comment]
Some cores need manual input activation, you can do so by calling, as an example, SetControllerPortDevice(0, RETRO_DEVICE.JOYPAD) on the LibretroInstance.

SetControllerPortDevice(uint port, RETRO_DEVICE id);

**Comment by Phantomxm2021** [comment]
Thank you very much. It's working!
